services:
  landing:
    container_name: landing
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - landing-network

networks:
  landing-network:
    driver: bridge